lib/bus_kiosk_web/router.ex
defmodule BusKioskWeb.Router do
  use BusKioskWeb, :router
  import Phoenix.LiveView.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :live_layout do
    plug :put_root_layout, {BusKioskWeb.LayoutView, :live}
  end

  scope "/", BusKioskWeb do
    pipe_through :browser

    scope "/" do
      pipe_through :live_layout
      live "/", HomeLive
      live "/nearby_stops", NearbyStopsLive
      live "/live", KioskLive
    end

    get "/saved_stops", SavedStopController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", BusKioskWeb do
  #   pipe_through :api
  # end
end

lib/bus_kiosk_web/live/home_live.ex
defmodule BusKioskWeb.HomeLive do
  use Phoenix.LiveView

  defmodule Params do
    defstruct [:stop_ids]

    def change(params) do
      types = %{
        stop_ids: :string,
        stop_ids_integers: {:array, :integer}
      }

      data = %Params{}

      changeset =
        Ecto.Changeset.cast({data, types}, params, [:stop_ids])
        |> Ecto.Changeset.validate_required([:stop_ids])

      stop_ids_integers =
        Ecto.Changeset.get_change(changeset, :stop_ids, "")
        |> String.trim_trailing(",")
        |> String.replace(", ", "")
        |> String.split(",")
        |> Enum.uniq()

      Ecto.Changeset.cast(changeset, %{stop_ids_integers: stop_ids_integers}, [:stop_ids_integers])
      |> Ecto.Changeset.validate_required([:stop_ids_integers])
      |> Ecto.Changeset.validate_length(:stop_ids_integers, min: 1, max: 4)
    end
  end

  def mount(_params, _session, socket) do
    changeset = Params.change(%{})
    socket = assign(socket, :changeset, changeset)

    {:ok, socket}
  end

  def handle_params(params, _uri, socket) do
    changeset = Params.change(params)
    socket = handle_changeset(socket, changeset)

    {:noreply, socket}
  end

  def handle_event("change", %{"params" => params}, socket) do
    changeset = Params.change(params)
    socket = handle_changeset(socket, changeset)

    socket =
      case Map.fetch(socket.assigns, :params) do
        {:ok, %{stop_ids_integers: _, stop_ids: text}} ->
          path =
            BusKioskWeb.Router.Helpers.live_path(socket, BusKioskWeb.HomeLive, %{
              stop_ids: text
            })

          push_patch(socket, to: path)

        _ ->
          socket
      end

    {:noreply, socket}
  end

  def handle_event("submit", _params, socket) do
    {:noreply,
     redirect(socket,
       to:
         BusKioskWeb.Router.Helpers.live_path(socket, BusKioskWeb.KioskLive, %{
           stop_ids: socket.assigns.params.stop_ids
         })
     )}
  end

  def render(assigns) do
    Phoenix.View.render(BusKioskWeb.HomeView, "page.html", assigns)
  end

  defp handle_changeset(socket, changeset) do
    case Ecto.Changeset.apply_action(changeset, :insert) do
      {:ok, params} ->
        assign(socket, :changeset, changeset)
        |> assign(:params, params)

      {:error, error_changeset} ->
        assign(socket, :changeset, error_changeset)
        |> assign(:params, nil)
    end
  end
end

lib/bus_kiosk_web/views/home_view.ex
defmodule BusKioskWeb.HomeView do
  use BusKioskWeb, :view
end

lib/bus_kiosk_web/templates/home/page.html.leex
<h1>BusMKE</h1>
<p class="notes">Type in up to 4 stop numbers and click the button to see live bus times!</p>
<p>If you're not sure what your stop numbers are, the map in the Ride MCTS app lets you click on stops to see their stop number.</p>
<%= form_for @changeset, "#", [phx_change: :change, phx_submit: :submit], fn f -> %>
  <fieldset>
      <%= label f, :stop_ids, "Stop Numbers (comma separated)" %>
      <%= text_input f, :stop_ids, placeholder: "64, 405" %>
      <div>
        <%= BusKioskWeb.ErrorHelpers.error_tag f, :stop_id_integers %>
      </div>

      <%= if @changeset.valid? do %>
        <%= submit "Get Buses!" %>
      <% else %>
        <%= submit "Get Buses!", disabled: true %>
      <% end %>
  </fieldset>
<% end %>
<div class="footer">
  <ul>
    <li>
      <%= link "My Saved Stops", to: Routes.saved_stop_path(BusKioskWeb.Endpoint, :index) %>
    </li>
    <li>
      <%= link "Stops Near Me (BETA)", to: Routes.live_path(@socket, BusKioskWeb.NearbyStopsLive) %>
    </li>
  </ul>
</div>
<div>
  <div>Coming Soon:</div>
  <ul>
    <li>A better interface for nearby stops</li>
    <li>Selecting specific routes at a stop</li>
  </ul>
</div>